//td1-- SQL script for hospital database schema and operations
-- Table HOPITAL
CREATE TABLE HOPITAL (
    CODE_HOPITAL VARCHAR(10) PRIMARY KEY,
    NOM_HOP VARCHAR(100) NOT NULL,
    WILAYA VARCHAR(50) NOT NULL,
    NB_SERVICE INTEGER,
    DATE_CREATION DATE
);

-- Table SERVICE
CREATE TABLE SERVICE (
    CODE_SERVICE VARCHAR(10) PRIMARY KEY,
    NOM_SERVICE VARCHAR(50) NOT NULL,
    BATIMENT VARCHAR(50),
    CODE_HOPITAL VARCHAR(10) NOT NULL,
    CONSTRAINT FK_SERVICE_HOPITAL FOREIGN KEY (CODE_HOPITAL) 
        REFERENCES HOPITAL(CODE_HOPITAL)
);

-- Table EMPLOYE
CREATE TABLE EMPLOYE (
    NUM_EMP VARCHAR(10) PRIMARY KEY,
    NOM_EMP VARCHAR(50) NOT NULL,
    PRENOM_EMP VARCHAR(50) NOT NULL,
    ADRESSE_EMP VARCHAR(200),
    TEL_EMP VARCHAR(15),
    CODE_SERVICE VARCHAR(10),
    CODE_HOPITAL VARCHAR(10),
    CONSTRAINT FK_EMPLOYE_SERVICE FOREIGN KEY (CODE_SERVICE) 
        REFERENCES SERVICE(CODE_SERVICE),
    CONSTRAINT FK_EMPLOYE_HOPITAL FOREIGN KEY (CODE_HOPITAL) 
        REFERENCES HOPITAL(CODE_HOPITAL)
);

-- Table INFIRMIER
CREATE TABLE INFIRMIER (
    NUM_INF VARCHAR(10) PRIMARY KEY,
    ROTATION VARCHAR(20),
    SALAIRE DECIMAL(10,2),
	NUM_EMP VARCHAR(10) NOT NULL,
    CONSTRAINT FK_INFIRMIER_EMPLOYE FOREIGN KEY (NUM_EMP) 
        REFERENCES EMPLOYE(NUM_EMP)
);

-- Table CHAMBRE
CREATE TABLE CHAMBRE (
    CODE_HOPITAL VARCHAR(10),
    CODE_SERVICE VARCHAR(10),
    NUM_CHAMBRE VARCHAR(10),
    NUM_INF VARCHAR(10),
    NB_LITS INTEGER,
    PRIMARY KEY (CODE_HOPITAL, CODE_SERVICE, NUM_CHAMBRE),
    CONSTRAINT FK_CHAMBRE_SERVICE FOREIGN KEY (CODE_SERVICE) 
        REFERENCES SERVICE(CODE_SERVICE),
    CONSTRAINT FK_CHAMBRE_HOPITAL FOREIGN KEY (CODE_HOPITAL) 
        REFERENCES HOPITAL(CODE_HOPITAL),
    CONSTRAINT FK_CHAMBRE_INFIRMIER FOREIGN KEY (NUM_INF) 
        REFERENCES INFIRMIER(NUM_INF)
);

-- Table MEDECIN
CREATE TABLE MEDECIN (
    NUM_MED VARCHAR(10) PRIMARY KEY,
    SPECIALITE VARCHAR(50),
    SALAIRE DECIMAL(10,2),
    NUM_EMP VARCHAR(10) NOT NULL,
    CONSTRAINT FK_MEDECIN_EMPLOYE FOREIGN KEY (NUM_EMP) 
        REFERENCES EMPLOYE(NUM_EMP)
);

-- Table PATIENT
CREATE TABLE PATIENT (
    NUM_PATIENT VARCHAR(10) PRIMARY KEY,
    NOM_PATIENT VARCHAR(50) NOT NULL,
    PRENOM_PATIENT VARCHAR(50) NOT NULL,
    ADRESSE_PATIENT VARCHAR(200),
    TEL_PATIENT VARCHAR(15),
    MUTUELLE VARCHAR(50),
    CODE_SERVICE VARCHAR(10),
    CONSTRAINT FK_PATIENT_SERVICE FOREIGN KEY (CODE_SERVICE) 
        REFERENCES SERVICE(CODE_SERVICE)
);

-- Table HOSPITALISATION
CREATE TABLE HOSPITALISATION (
    NUM_PATIENT VARCHAR(10),
    DATE_HOSP DATE,
    CODE_SERVICE VARCHAR(10),
    CODE_HOPITAL VARCHAR(10),
    NUM_CHAMBRE VARCHAR(10),
    LIT INTEGER,
    PRIMARY KEY (NUM_PATIENT, DATE_HOSP),
    CONSTRAINT FK_HOSP_PATIENT FOREIGN KEY (NUM_PATIENT) 
        REFERENCES PATIENT(NUM_PATIENT),
    CONSTRAINT FK_HOSP_SERVICE FOREIGN KEY (CODE_SERVICE) 
        REFERENCES SERVICE(CODE_SERVICE),
    CONSTRAINT FK_HOSP_HOPITAL FOREIGN KEY (CODE_HOPITAL) 
        REFERENCES HOPITAL(CODE_HOPITAL),
    CONSTRAINT FK_HOSP_CHAMBRE FOREIGN KEY (CODE_HOPITAL, CODE_SERVICE, NUM_CHAMBRE) 
        REFERENCES CHAMBRE(CODE_HOPITAL, CODE_SERVICE, NUM_CHAMBRE)
);

-- Table SOIGNE
CREATE TABLE SOIGNE (
    NUM_PATIENT VARCHAR(10),
    NUM_MED VARCHAR(10),
    PRIMARY KEY (NUM_PATIENT, NUM_MED),
    CONSTRAINT FK_SOIGNE_PATIENT FOREIGN KEY (NUM_PATIENT) 
        REFERENCES PATIENT(NUM_PATIENT),
    CONSTRAINT FK_SOIGNE_MEDECIN FOREIGN KEY (NUM_MED) 
        REFERENCES MEDECIN(NUM_MED)
);


ALTER TABLE EMPLOYE ADD DATE_NAISSANCE DATE;


ALTER TABLE HOPITAL DROP COLUMN DATE_CREATION;



-- Contrainte sur le salaire d'un employé (via MEDECIN et INFIRMIER)
ALTER TABLE MEDECIN ADD CONSTRAINT CHK_SALAIRE_MED 
    CHECK (SALAIRE >= 46000);

ALTER TABLE INFIRMIER ADD CONSTRAINT CHK_SALAIRE_INF 
	CHECK (SALAIRE >= 35000);






INSERT INTO HOPITAL (CODE_HOPITAL, NOM_HOP, WILAYA, NB_SERVICE) 
VALUES ('MUST', 'Hôpital universitaire Mustapha Pacha', 'Alger', 25);

INSERT INTO HOPITAL (CODE_HOPITAL, NOM_HOP, WILAYA, NB_SERVICE) 
VALUES ('BMS', 'Hôpital Aissat IDIR, Beni Messous', 'Alger', 22);

INSERT INTO HOPITAL (CODE_HOPITAL, NOM_HOP, WILAYA, NB_SERVICE) 
VALUES ('ORN', 'Hôpital Universitaire d''Oran', 'Oran', 19);



UPDATE EMPLOYE
SET CODE_HOPITAL = 'ORN' 
WHERE NOM_EMP = 'BAKIR' AND PRENOM_EMP = 'Adel';




UPDATE CHAMBRE
SET NB_LITS = NB_LITS + 1  -- ou une valeur spécifique
WHERE NUM_CHAMBRE = '13' 
  AND CODE_SERVICE = (SELECT CODE_SERVICE FROM SERVICE 
                      WHERE NOM_SERVICE = 'REA' AND CODE_HOPITAL = 'BMS')
	AND CODE_HOPITAL = 'BMS';




-- Attention : il faut d'abord supprimer les références dans les tables dépendantes
DELETE FROM SOIGNE 
WHERE NUM_MED IN (SELECT M.NUM_MED FROM MEDECIN M 
                  JOIN EMPLOYE E ON M.NUM_EMP = E.NUM_EMP 
                  WHERE E.CODE_HOPITAL = 'MUST');



DELETE FROM MEDECIN 
WHERE NUM_EMP IN (SELECT NUM_EMP FROM EMPLOYE WHERE CODE_HOPITAL = 'MUST');



DELETE FROM INFIRMIER 
WHERE NUM_EMP IN (SELECT NUM_EMP FROM EMPLOYE WHERE CODE_HOPITAL = 'MUST');



DELETE FROM EMPLOYE 
WHERE CODE_HOPITAL = 'MUST';


SELECT E.NOM_EMP, E.PRENOM_EMP, E.TEL_EMP
FROM EMPLOYE E
JOIN SERVICE S ON E.CODE_SERVICE = S.CODE_SERVICE
JOIN HOPITAL H ON S.CODE_HOPITAL = H.CODE_HOPITAL
WHERE S.NOM_SERVICE = 'Cardio' 
	AND H.NOM_HOP = 'Hôpital universitaire Mustapha Pacha';


SELECT COUNT(*) AS NB_HOSPITALISATIONS
FROM HOSPITALISATION H
JOIN SERVICE S ON H.CODE_SERVICE = S.CODE_SERVICE
WHERE S.NOM_SERVICE = 'Pédiatrie' 
	AND H.CODE_HOPITAL = 'ORN';


SELECT M.NUM_MED, M.SPECIALITE, E.NOM_EMP, E.PRENOM_EMP,
       COUNT(DISTINCT S.NUM_PATIENT) AS NB_PATIENTS
FROM MEDECIN M
JOIN EMPLOYE E ON M.NUM_EMP = E.NUM_EMP
LEFT JOIN SOIGNE S ON M.NUM_MED = S.NUM_MED
GROUP BY M.NUM_MED, M.SPECIALITE, E.NOM_EMP, E.PRENOM_EMP
ORDER BY M.SPECIALITE, NB_PATIENTS DESC;


SELECT H.CODE_HOPITAL, H.NOM_HOP, SUM(C.NB_LITS) AS TOTAL_LITS
FROM HOPITAL H
LEFT JOIN CHAMBRE C ON H.CODE_HOPITAL = C.CODE_HOPITAL
GROUP BY H.CODE_HOPITAL, H.NOM_HOP
ORDER BY TOTAL_LITS DESC;


-- Les index primaires sont automatiquement créés avec les PRIMARY KEY
-- Mais on peut créer des index secondaires utiles :

CREATE INDEX IDX_EMPLOYE_SERVICE ON EMPLOYE(CODE_SERVICE);
CREATE INDEX IDX_EMPLOYE_HOPITAL ON EMPLOYE(CODE_HOPITAL);
CREATE INDEX IDX_SERVICE_HOPITAL ON SERVICE(CODE_HOPITAL);
CREATE INDEX IDX_PATIENT_SERVICE ON PATIENT(CODE_SERVICE);
CREATE INDEX IDX_HOSP_PATIENT ON HOSPITALISATION(NUM_PATIENT);
CREATE INDEX IDX_HOSP_SERVICE ON HOSPITALISATION(CODE_SERVICE);
CREATE INDEX IDX_SOIGNE_PATIENT ON SOIGNE(NUM_PATIENT);
CREATE INDEX IDX_SOIGNE_MEDECIN ON SOIGNE(NUM_MED);


CREATE VIEW V_SERVICES_CARDIO AS
SELECT S.CODE_SERVICE, S.NOM_SERVICE, S.BATIMENT, 
       H.CODE_HOPITAL, H.NOM_HOP, H.WILAYA
FROM SERVICE S
JOIN HOPITAL H ON S.CODE_HOPITAL = H.CODE_HOPITAL
WHERE S.NOM_SERVICE LIKE '%Cardio%';




CREATE VIEW V_PATIENTS_PEDIATRIE_BMS AS
SELECT DISTINCT P.NUM_PATIENT, P.NOM_PATIENT, P.PRENOM_PATIENT, 
       P.ADRESSE_PATIENT, P.TEL_PATIENT, P.MUTUELLE
FROM PATIENT P
JOIN HOSPITALISATION H ON P.NUM_PATIENT = H.NUM_PATIENT
JOIN SERVICE S ON H.CODE_SERVICE = S.CODE_SERVICE
WHERE S.NOM_SERVICE = 'Pédiatrie' 
	AND H.CODE_HOPITAL = 'BMS';


-- Catalogue des tables
SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'votre_schema';

-- Catalogue des colonnes
SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_SCHEMA = 'votre_schema';

-- Catalogue des contraintes
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE TABLE_SCHEMA = 'votre_schema';

-- Catalogue des clés étrangères
SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS 
WHERE CONSTRAINT_SCHEMA = 'votre_schema';

-- Catalogue des index
SELECT * FROM INFORMATION_SCHEMA.STATISTICS 
WHERE TABLE_SCHEMA = 'votre_schema';

-- Catalogue des vues
SELECT * FROM INFORMATION_SCHEMA.VIEWS 
WHERE TABLE_SCHEMA = 'votre_schema';



