TP 2 - PRIVILÈGES ET SÉCURITÉ
QUESTIONS 1-3 : CRÉATION UTILISATEUR ET CONNEXION
-- Q1: Créer l'utilisateur (en tant que DBA)
CREATE USER GERERTP2
IDENTIFIED BY motdepasse456
DEFAULT TABLESPACE BENALI_TBS
TEMPORARY TABLESPACE BENALI_TEMPTBS;

-- Q2: Tentative de connexion
-- REMARQUE : Échec car l'utilisateur n'a pas le privilège CREATE SESSION

-- Q3: Donner le droit de connexion
GRANT CREATE SESSION TO GERERTP2;

-- Maintenant la connexion réussit


QUESTION 4 : DONNER PRIVILÈGES DE CRÉATION
GRANT CREATE TABLE TO GERERTP2;

GRANT CREATE USER TO GERERTP2;

-- Vérification
SELECT
    *
FROM
    DBA_SYS_PRIVS
WHERE
	GRANTEE = 'GERERTP2';


QUESTIONS 5-6 : PRIVILÈGES SUR OBJETS
-- Q5: Exécuter en tant que GererTP2
SELECT
    *
FROM
    TP1_BENALI.ETUDIANT;

-- REMARQUE : ORA-00942 (table ou vue n'existe pas) car pas de privilège SELECT

-- Q6: Donner le droit de lecture (exécuter en tant que TP1_Benali)
GRANT SELECT ON ETUDIANT TO GERERTP2;

-- Maintenant la requête fonctionne
SELECT
    *
FROM
	TP1_BENALI.ETUDIANT;


QUESTIONS 7-8 : RÉVOCATION DE PRIVILÈGES
-- Q7: Enlever les privilèges
REVOKE SELECT ON ETUDIANT FROM GERERTP2;

REVOKE CREATE TABLE FROM GERERTP2;

-- Q8: Vérification
SELECT
    *
FROM
    DBA_TAB_PRIVS
WHERE
    GRANTEE = 'GERERTP2';

SELECT
    *
FROM
    DBA_SYS_PRIVS
WHERE
	GRANTEE = 'GERERTP2';


QUESTION 9 : CRÉER UN PROFIL
CREATE PROFILE GERER_DROITTP2 LIMIT
    SESSIONS_PER_USER 3
    CPU_PER_CALL 3000 -- 30 secondes = 3000 centisecondes
    CONNECT_TIME 30 -- 30 minutes
    LOGICAL_READS_PER_CALL 1500
    PRIVATE_SGA 25K
    IDLE_TIME 40 -- 40 minutes
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 80 -- 80 jours
    PASSWORD_REUSE_TIME 60 -- 60 jours
    PASSWORD_LOCK_TIME 1 -- 1 jour
	PASSWORD_GRACE_TIME 25;-- 25 jours



QUESTION 10 : AFFECTER LE PROFIL
ALTER USER GERERTP2 PROFILE GERER_DROITTP2;

QUESTIONS 11-12 : PRIVILÈGES UPDATE
-- Q11: Tenter une modification
UPDATE TP1_BENALI.ETUDIANT
SET
    NOMETU = 'NOUVEAU'
WHERE
    MATRICULEETU = 'E001';

-- REMARQUE : Échec - privilège UPDATE manquant

-- Q12: Donner le droit UPDATE
GRANT UPDATE ON ETUDIANT TO GERERTP2;

-- Réessayer la modification
UPDATE TP1_BENALI.ETUDIANT
SET
    NOMETU = 'NOUVEAU'
WHERE
    MATRICULEETU = 'E001';

-- Réussi

QUESTIONS 13-14 : CRÉATION ET AFFECTATION DE RÔLE
-- Q13: Créer le rôle
CREATE ROLE GESTIONTP2;

-- Attribuer des privilèges au rôle
GRANT SELECT ON TP1_BENALI.ETUDIANT TO GESTIONTP2;

GRANT SELECT ON TP1_BENALI.MODULE TO GESTIONTP2;

GRANT UPDATE ON TP1_BENALI.INSCRIPTION TO GESTIONTP2;

-- Q14: Assigner le rôle à l'utilisateur
GRANT GESTIONTP2 TO GERERTP2;

-- Vérification
SELECT
    *
FROM
    DBA_ROLE_PRIVS
WHERE
    GRANTEE = 'GERERTP2';

SELECT
    *
FROM
    ROLE_TAB_PRIVS
WHERE
	ROLE = 'GESTIONTP2';

QUESTIONS 15-16 : CRÉATION D''index
-- Q15: Tenter de créer un index
CREATE INDEX IDX_NOM_ETU ON TP1_BENALI.ETUDIANT(NOMETU);

-- REMARQUE : Échec - privilège INDEX manquant

-- Q16: Donner le privilège INDEX
GRANT INDEX ON ETUDIANT TO GESTIONTP2;

-- Réessayer
CREATE INDEX IDX_NOM_ETU ON TP1_BENALI.ETUDIANT(NOMETU);

-- Réussi


NOTES IMPORTANTES
BONNES PRATIQUES
TOUJOURS TESTER LES CONTRAINTES AVEC DES DONNÉES INVALIDES
UTILISER DES NOMS EXPLICITES POUR LES CONTRAINTES
DOCUMENTER LES PRIVILÈGES ACCORDÉS
SAUVEGARDER RÉGULIÈREMENT AVEC COMMIT

COMMANDES UTILES
-- Voir les contraintes d'une table
SELECT
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    SEARCH_CONDITION
FROM
    USER_CONSTRAINTS
WHERE
    TABLE_NAME = 'ETUDIANT';

-- Voir les privilèges d'un utilisateur
SELECT
    *
FROM
    USER_TAB_PRIVS;

SELECT
    *
FROM
    USER_SYS_PRIVS;

-- Voir les rôles
SELECT
    *
FROM
    USER_ROLE_PRIVS;