-- Table Departement
CREATE TABLE DEPARTEMENT (
    CODEDEPT VARCHAR2(10) PRIMARY KEY,
    NOMDEPT VARCHAR2(50) NOT NULL,
    NOMCHEF VARCHAR2(50)
);

-- Table Specialite avec C1
CREATE TABLE SPECIALITE (
    CODESPEC VARCHAR2(10) PRIMARY KEY,
    NOMSPEC VARCHAR2(50) NOT NULL,
    NBETUDIANTS NUMBER DEFAULT 0,
    CODEDEPT VARCHAR2(10),
    CONSTRAINT FK_SPEC_DEPT FOREIGN KEY (CODEDEPT) REFERENCES DEPARTEMENT(CODEDEPT) ON DELETE CASCADE,
    CONSTRAINT CHK_CODE_SPEC CHECK (CODESPEC IN ('RSD', 'SII', 'SSI', 'IL')),
    CONSTRAINT CHK_NB_ETU CHECK (NBETUDIANTS < 100) -- C2
);

-- Table Etudiant
CREATE TABLE ETUDIANT (
    MATRICULEETU VARCHAR2(15) PRIMARY KEY,
    NOMETU VARCHAR2(30) NOT NULL,
    PRENOMETU VARCHAR2(30) NOT NULL,
    DATENAISSANCE DATE,
    CODESPEC VARCHAR2(10),
    CONSTRAINT FK_ETU_SPEC FOREIGN KEY (CODESPEC) REFERENCES SPECIALITE(CODESPEC) ON DELETE SET NULL
);

-- Table Enseignant
CREATE TABLE ENSEIGNANT (
    MATRICULEENS VARCHAR2(15) PRIMARY KEY,
    NOMENS VARCHAR2(30) NOT NULL,
    PRENOMENS VARCHAR2(30) NOT NULL,
    DATENAISSANCE DATE,
    DATERECRUTEMENT DATE,
    CODEDEPT VARCHAR2(10),
    CONSTRAINT FK_ENS_DEPT FOREIGN KEY (CODEDEPT) REFERENCES DEPARTEMENT(CODEDEPT)
);

-- Table Module
CREATE TABLE MODULE (
    CODEMODULE VARCHAR2(10) PRIMARY KEY,
    NOMMODULE VARCHAR2(50) NOT NULL,
    COEFFICIENT NUMBER(2),
    CODESPEC VARCHAR2(10),
    CONSTRAINT FK_MOD_SPEC FOREIGN KEY (CODESPEC) REFERENCES SPECIALITE(CODESPEC)
);

-- Table Inscription (Clé primaire composée)
CREATE TABLE INSCRIPTION (
    MATRICULEETU VARCHAR2(15),
    CODEMODULE VARCHAR2(10),
    DATEINSCRIPTION DATE DEFAULT SYSDATE,
    NOTE NUMBER(4, 2),
    CONSTRAINT PK_INSCRIPTION PRIMARY KEY (MATRICULEETU, CODEMODULE),
    CONSTRAINT FK_INSC_ETU FOREIGN KEY (MATRICULEETU) REFERENCES ETUDIANT(MATRICULEETU) ON DELETE CASCADE,
    CONSTRAINT FK_INSC_MOD FOREIGN KEY (CODEMODULE) REFERENCES MODULE(CODEMODULE) ON DELETE CASCADE,
    CONSTRAINT CHK_NOTE CHECK (NOTE BETWEEN 0 AND 20)
);