-- SE CONNECTER EN TANT QUE DBA (SYSTEM ou SYS)
CONNECT SYSTEM/password_system;

-- Créer l'utilisateur GererTP2
CREATE USER GERERTP2
IDENTIFIED BY motdepasse456
DEFAULT TABLESPACE BENALI_TBS
TEMPORARY TABLESPACE BENALI_TEMPTBS;

-- Confirmation
-- User created.