SCHÉMA CONCEPTUEL DES 6 TABLES :
DEPARTEMENT (CODEDEPT, NOMDEPT, NOMCHEF)
SPECIALITE (CODESPEC, NOMSPEC, CODEDEPT#)
ETUDIANT (MATRICULEETU, NOMETU, PRENOMETU, DATENAISSANCE, CODESPEC#)
ENSEIGNANT (MATRICULEENS, NOMENS, PRENOMENS, DATERECRUTEMENT, CODEDEPT#)
MODULE (CODEMODULE, NOMMODULE, COEFFICIENT, CODESPEC#)
INSCRIPTION (MATRICULEETU#, CODEMODULE#, DATEINSCRIPTION, NOTE) - CLÉ PRIMAIRE COMPOSÉE