SELECT
    E.CODESPEC,
    S.NOMSPEC,
    COUNT(*)    AS NOMBREETUDIANTS,
    AVG(I.NOTE) AS MOYENNEGENERALE,
    MAX(I.NOTE) AS MEILLEURENOTE,
    MIN(I.NOTE) AS PLUSBASSENOTE
FROM
    ETUDIANT    E
    JOIN INSCRIPTION I
	ON E.MATRICULEETU = I.MATRICULEETU
    JOIN SPECIALITE S
    ON E.CODESPEC = S.CODESPEC
GROUP BY
    E.CODESPEC,
    S.NOMSPEC
HAVING
    AVG(I.NOTE) >= 12
ORDER BY
    MOYENNEGENERALE DESC;