SELECT
    E.MATRICULEETU,
    E.NOMETU,
    E.PRENOMETU,
    M.NOMMODULE,
    I.NOTE,
    S.NOMSPEC
FROM
	ETUDIANT E
    JOIN INSCRIPTION I
    ON E.MATRICULEETU = I.MATRICULEETU
    JOIN MODULE M
    ON I.CODEMODULE = M.CODEMODULE
    JOIN SPECIALITE S
    ON E.CODESPEC = S.CODESPEC
WHERE
    I.NOTE >= 10
    AND S.CODESPEC IN ('RSD', 'IL')
ORDER BY
    E.NOMETU;