-- Création de la vue
CREATE VIEW VUE_STATS_SPECIALITES AS
    SELECT
        E.CODESPEC,
        S.NOMSPEC,
        COUNT(*)    AS NOMBREETUDIANTS,
        AVG(I.NOTE) AS MOYENNEGENERALE,
        MAX(I.NOTE) AS MEILLEURENOTE,
        MIN(I.NOTE) AS PLUSBASSENOTE
    FROM
        ETUDIANT    E
        JOIN INSCRIPTION I
        ON E.MATRICULEETU = I.MATRICULEETU
        JOIN SPECIALITE S
        ON E.CODESPEC = S.CODESPEC
	GROUP BY
        E.CODESPEC,
        S.NOMSPEC;

-- Interroger la vue
SELECT
    *
FROM
    VUE_STATS_SPECIALITES
WHERE
    MOYENNEGENERALE >= 12
ORDER BY
    MOYENNEGENERALE DESC;