-- En tant que DBA
CREATE TABLESPACE BENALI_TBS
DATAFILE 'C:\tbs_benali.dat'
SIZE 100M
AUTOEXTEND ON
ONLINE;

CREATE TEMPORARY TABLESPACE BENALI_TEMPTBS
TEMPFILE 'C:\temp_benali.dat'
SIZE 100M
AUTOEXTEND ON;

